# Generated by Django 3.1.6 on 2021-02-11 11:07

from django.db import migrations


"""
data migration file = direct manipulation of data into the database.
"""

def create_data(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Student(
        name="Joe Silver",
        email="joe@email.com",
        document="22342342",
        phone="00000000",
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_students"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
